<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import type { Report, ReportSection } from '../../types/report'

const props = defineProps<{
  report: Report
  reportId: string
  version: number
}>()

const emit = defineEmits<{
  close: []
  regenerate: [sectionId: string, reportId: string]
  print: []
}>()

const sections = ref<ReportSection[]>([...props.report.sections])

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape') emit('close')
}
onMounted(() => document.addEventListener('keydown', handleKeydown))
onUnmounted(() => document.removeEventListener('keydown', handleKeydown))

function handleRegenerate(sectionId: string) {
  emit('regenerate', sectionId, props.reportId)
}

function updateSection(sectionId: string, newSection: ReportSection) {
  const idx = sections.value.findIndex(s => s.id === sectionId)
  if (idx !== -1) {
    sections.value[idx] = newSection
  }
}

defineExpose({ updateSection })
</script>

<template>
  <Teleport to="body">
    <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm" @click.self="emit('close')">
      <div class="relative w-full max-w-4xl max-h-[90vh] bg-white dark:bg-gray-900 rounded-2xl shadow-2xl flex flex-col overflow-hidden">
        <!-- Header -->
        <div class="flex items-center justify-between px-6 py-4 border-b border-gray-200 dark:border-gray-700 shrink-0">
          <div class="min-w-0">
            <h2 class="text-lg font-semibold truncate">{{ report.meta.title }}</h2>
            <p v-if="report.meta.subtitle" class="text-sm text-gray-500 dark:text-gray-400 truncate">
              {{ report.meta.subtitle }}
            </p>
          </div>
          <div class="flex items-center gap-2 shrink-0 ml-4">
            <UButton
              size="xs"
              variant="soft"
              icon="i-lucide-download"
              @click="emit('print')"
            >
              PDF
            </UButton>
            <UBadge variant="soft" size="xs">
              v{{ version }}
            </UBadge>
            <UBadge color="primary" variant="soft" size="xs">
              {{ report.meta.pageTarget }} pages
            </UBadge>
            <UButton
              variant="ghost"
              icon="i-lucide-x"
              size="sm"
              @click="emit('close')"
            />
          </div>
        </div>

        <!-- Scrollable content -->
        <div class="flex-1 overflow-y-auto px-6 py-6 space-y-6">
          <template v-for="section in sections" :key="section.id">
            <ReportSectionWrapper
              v-if="section.type !== 'cover'"
              :section-id="section.id"
              :section-type="section.type"
              :title="section.title"
              @regenerate="handleRegenerate"
            >
              <ReportExecSummary v-if="section.type === 'executive_summary'" :section="section" />
              <ReportKpiDashboard v-else-if="section.type === 'kpi_dashboard'" :section="section" />
              <ReportChart v-else-if="section.type === 'chart'" :section="section" />
              <ReportTable v-else-if="section.type === 'table'" :section="section" />
              <ReportContent v-else-if="section.type === 'content'" :section="section" />
              <ReportRecommendations v-else-if="section.type === 'recommendations'" :section="section" />
              <ReportTimeline v-else-if="section.type === 'timeline'" :section="section" />
              <ReportComparison v-else-if="section.type === 'comparison'" :section="section" />
            </ReportSectionWrapper>

            <ReportCover v-else :section="section" :all-sections="sections" :branding="report.meta.branding" :language="report.meta.language" />
          </template>
        </div>

        <!-- Footer -->
        <div class="flex items-center justify-between px-6 py-3 border-t border-gray-200 dark:border-gray-700 text-xs text-gray-400 shrink-0">
          <span>Generated by {{ report.meta.author }} | {{ report.meta.generatedAt?.split('T')[0] }}</span>
          <span>Report ID: {{ reportId }}</span>
        </div>
      </div>
    </div>
  </Teleport>
</template>
